[project]
name = "plex-lazytv"
version = "1.0.0"
description = "A Tautulli script for generating smart random unwatched episodes playlists."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "plexapi>=4.17.1",
]

[dependency-groups]
dev = [
    "pdbp>=1.8.1",
]
